package pe.uc.efgrupo20.view;

import javax.swing.JInternalFrame;
import pe.uc.efgrupo20.model.EmpleadoModel;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/c/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware/
 */
public class MainView extends javax.swing.JFrame {

	/**
	 * Creates new form MainView
	 */
	public MainView() {
		initComponents();
		establecerTitulo();
		this.setExtendedState(MAXIMIZED_BOTH);
	}

	private void establecerTitulo() {
		EmpleadoModel bean = (EmpleadoModel) Session.get("usuario");
		this.setTitle("EUREKA APP (Usuario:" + bean.getUsuario() + ")");
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      desktopPane = new javax.swing.JDesktopPane();
      menuBar = new javax.swing.JMenuBar();
      fileMenu = new javax.swing.JMenu();
      exitMenuItem = new javax.swing.JMenuItem();
      menuProcesos = new javax.swing.JMenu();
      menuProcesosDeposito = new javax.swing.JMenuItem();
      menuProcesosRetiro = new javax.swing.JMenuItem();
      menuProcesosConMovimientos = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      fileMenu.setMnemonic('f');
      fileMenu.setText("File");

      exitMenuItem.setMnemonic('x');
      exitMenuItem.setText("Exit");
      exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitMenuItemActionPerformed(evt);
         }
      });
      fileMenu.add(exitMenuItem);

      menuBar.add(fileMenu);

      menuProcesos.setText("Procesos");

      menuProcesosDeposito.setText("Depósito");
      menuProcesosDeposito.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuProcesosDepositoActionPerformed(evt);
         }
      });
      menuProcesos.add(menuProcesosDeposito);

      menuProcesosRetiro.setText("Retiro");
      menuProcesosRetiro.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuProcesosRetiroActionPerformed(evt);
         }
      });
      menuProcesos.add(menuProcesosRetiro);

      menuProcesosConMovimientos.setText("Consulta movimientos");
      menuProcesosConMovimientos.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuProcesosConMovimientosActionPerformed(evt);
         }
      });
      menuProcesos.add(menuProcesosConMovimientos);

      menuBar.add(menuProcesos);

      setJMenuBar(menuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		 System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

   private void menuProcesosDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosDepositoActionPerformed
		/*
		JInternalFrame view = new ProcDepositoView();
		desktopPane.add(view);
		view.setVisible(true);
		*/
		cargarFormulario(ProcDepositoView.class);
   }//GEN-LAST:event_menuProcesosDepositoActionPerformed

   private void menuProcesosRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosRetiroActionPerformed
      cargarFormulario(ProcRetiroView.class);
   }//GEN-LAST:event_menuProcesosRetiroActionPerformed

   private void menuProcesosConMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosConMovimientosActionPerformed
      cargarFormulario(ConsultaMovimientosView.class);
   }//GEN-LAST:event_menuProcesosConMovimientosActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JDesktopPane desktopPane;
   private javax.swing.JMenuItem exitMenuItem;
   private javax.swing.JMenu fileMenu;
   private javax.swing.JMenuBar menuBar;
   private javax.swing.JMenu menuProcesos;
   private javax.swing.JMenuItem menuProcesosConMovimientos;
   private javax.swing.JMenuItem menuProcesosDeposito;
   private javax.swing.JMenuItem menuProcesosRetiro;
   // End of variables declaration//GEN-END:variables

	private void cargarFormulario(Class<?> aClass) {
		try {
			// Buscar una instancia
			JInternalFrame view = null;
			for (JInternalFrame frame : desktopPane.getAllFrames()) {
				if (aClass.isInstance(frame)) {
					view = frame;
					break;
				}
			}
			// Crear la instancia
			if (view == null) {
				view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
				desktopPane.add(view);
			}
			// Hacerlo visible
			view.setVisible(true);
			view.setSelected(true);
			view.setMaximum(true);
		} catch (Exception e) {
		}

	}
}
